/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideIndex: typeof import('./src/components/Layout/aside/asideIndex.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    HeaderIndex: typeof import('./src/components/Layout/header/headerIndex.vue')['default']
    HerderRight: typeof import('./src/components/Layout/header/herderRight.vue')['default']
    LayoutIndex: typeof import('./src/components/Layout/layoutIndex.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MenuIndex: typeof import('./src/components/Layout/menu/menuIndex.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./src/components/Layout/menu/menutsx/subMenu.tsx')['default']
    Svg: typeof import('./src/components/Svg.vue')['default']
  }
}
